import anthropic
from django.conf import settings


def _get_client():
    # Initialize the Anthropic client lazily so missing credentials fail only on use.
    api_key = settings.ANTHROPIC_API_KEY
    if not api_key:
        raise ValueError("ANTHROPIC_API_KEY is not configured")
    return anthropic.Anthropic(api_key=api_key)


NEUTRALITY_DISCLAIMER = (
    "\n\n*Generated by AI from public sources. Always verify independently.*"
)


def generate_bio(rep) -> str:
    """Generate a neutral biographical summary for a representative."""
    client = _get_client()
    # Phrase the prompt differently for senators vs. House members.
    level_label = "US Senator" if rep.level == "senate" else "US House Representative"

    prompt = f"""Write a neutral, factual biographical summary for {rep.name}, a {level_label}
from {rep.state} representing the {rep.party.capitalize()} party.

Include:
- Their role and district/state they represent
- Years in office (if known)
- Professional background and career highlights
- Key committee assignments (if known)
- Contact information placeholder

Keep it under 300 words. Use neutral, non-partisan language. If you are uncertain about
specific facts, say so explicitly. Do not endorse or criticize any political positions.
Cite public record sources where possible."""

    message = client.messages.create(
        model="claude-sonnet-4-6",
        max_tokens=500,
        messages=[{"role": "user", "content": prompt}]
    )

    # Anthropic returns structured content blocks; this app uses the first text block.
    content = message.content[0].text
    return content + NEUTRALITY_DISCLAIMER


def generate_voting_record_summary(rep) -> str:
    """Generate a neutral voting record summary."""
    client = _get_client()
    level_label = "US Senator" if rep.level == "senate" else "US House Representative"

    prompt = f"""Provide a neutral summary of the voting record and legislative activity of
{rep.name}, a {level_label} from {rep.state} ({rep.party.capitalize()} party).

Include:
- General voting patterns on major issue areas (without editorializing)
- Notable bills sponsored or cosponsored
- Party-line vs. bipartisan voting frequency
- Key policy areas they've focused on

Keep it under 400 words. Present facts only, no opinions. If you lack specific data,
acknowledge that explicitly. Use language like "voted in favor of" or "opposed" rather
than characterizing positions as good or bad. Reference public voting records from Congress.gov."""

    message = client.messages.create(
        model="claude-sonnet-4-6",
        max_tokens=600,
        messages=[{"role": "user", "content": prompt}]
    )

    content = message.content[0].text
    return content + NEUTRALITY_DISCLAIMER


def generate_how_to_vote(rep) -> str:
    """Generate voter information specific to the representative's state."""
    client = _get_client()

    prompt = f"""Provide practical voter information for residents of {rep.state} who are
represented by {rep.name}.

Include:
- How to register to vote in {rep.state}
- Voter registration deadlines (general election)
- Types of voting available (in-person, mail-in, early voting)
- How to find your polling location in {rep.state}
- Key election dates for {rep.state}
- Official {rep.state} voter information website

Keep it under 400 words. Be factual and helpful. If you are uncertain about specific
current deadlines, say so and direct users to the official state election website.
Do not discuss candidate positions or encourage voting for any particular candidate."""

    message = client.messages.create(
        model="claude-sonnet-4-6",
        max_tokens=600,
        messages=[{"role": "user", "content": prompt}]
    )

    content = message.content[0].text
    return content + NEUTRALITY_DISCLAIMER
