[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements/prod.txt && python manage.py collectstatic --noinput"

[deploy]
startCommand = "/entrypoint.sh"
healthcheckPath = "/api/health/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
