import { useState, useEffect } from 'react'
import { fetchRepSummary } from '../../api/representatives'
import type { AISummary } from '../../types'

type SummaryType = 'bio' | 'voting_record' | 'how_to_vote'

interface Props {
  repId: number
  type: SummaryType
}

export default function AISummaryTab({ repId, type }: Props) {
  const [loading, setLoading] = useState(true)
  const [summary, setSummary] = useState<AISummary | null>(null)
  const [error, setError] = useState<string | null>(null)

  useEffect(() => {
    let cancelled = false
    setLoading(true)
    setSummary(null)
    setError(null)

    fetchRepSummary(repId, type)
      .then((data) => { if (!cancelled) setSummary(data) })
      .catch(() => { if (!cancelled) setError('Unable to load AI summary. Please try again.') })
      .finally(() => { if (!cancelled) setLoading(false) })

    return () => { cancelled = true }
  }, [repId, type])

  return (
    <div className="ai-summary-tab">
      {loading && (
        <div
          className="ai-summary-loading"
          aria-busy="true"
          aria-label="Loading AI summary"
        >
          <div className="ai-summary-skeleton" />
          <div className="ai-summary-skeleton" />
          <div className="ai-summary-skeleton ai-summary-skeleton--short" />
        </div>
      )}

      {!loading && error && (
        <p className="ai-summary-error" role="alert">{error}</p>
      )}

      {!loading && summary && (
        <p className="ai-summary-text">{summary.content}</p>
      )}

      <aside className="ai-disclaimer" role="note">
        Generated by AI from public sources. Always verify independently.
      </aside>
    </div>
  )
}
