# Generated by Django 4.2.16 on 2026-03-09 17:59

from django.db import migrations, models
import django.db.models.deletion
import representatives.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Representative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('level', models.CharField(choices=[('house', 'US House'), ('senate', 'US Senate')], max_length=10)),
                ('party', models.CharField(choices=[('democrat', 'Democrat'), ('republican', 'Republican'), ('independent', 'Independent'), ('other', 'Other')], max_length=20)),
                ('state', models.CharField(max_length=2)),
                ('district_number', models.IntegerField(blank=True, null=True)),
                ('photo_url', models.URLField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('social_links', representatives.models.JSONTextField(default=dict)),
                ('term_start', models.DateField(blank=True, null=True)),
                ('term_end', models.DateField(blank=True, null=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('external_ids', representatives.models.JSONTextField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['state', 'level', 'district_number'],
            },
        ),
        migrations.CreateModel(
            name='AISummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('bio', 'Bio'), ('voting_record', 'Voting Record'), ('how_to_vote', 'How to Vote')], max_length=20)),
                ('content', models.TextField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('model_version', models.CharField(default='claude-opus-4-5', max_length=50)),
                ('representative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summaries', to='representatives.representative')),
            ],
            options={
                'unique_together': {('representative', 'content_type')},
            },
        ),
    ]
