# Generated by Django 4.2.16 on 2026-03-25 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('representatives', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('is_syncing', models.BooleanField(default=False)),
                ('last_error', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'sync status',
            },
        ),
    ]
