# Generated by Django 4.2.16 on 2026-03-28 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('representatives', '0003_representative_office_room_committees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='representative',
            name='district_number',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='representative',
            name='level',
            field=models.CharField(choices=[('house', 'US House'), ('senate', 'US Senate')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='representative',
            name='state',
            field=models.CharField(db_index=True, max_length=2),
        ),
    ]
