# Generated by Django 4.2.16 on 2026-03-28 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('representatives', '0004_alter_representative_district_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='representative',
            name='committee_assignments',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='representative',
            name='external_ids',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='representative',
            name='social_links',
            field=models.JSONField(default=dict),
        ),
    ]
