# Generated by Django 4.2.16 on 2026-03-30 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('representatives', '0005_alter_representative_committee_assignments_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AISummary',
        ),
    ]
