# Generated by Django 4.2.16 on 2026-05-29 03:37

from django.db import migrations, models


def forwards(apps, schema_editor):
    Representative = apps.get_model('representatives', 'Representative')
    Representative.objects.filter(level='house').update(level='us_house')
    Representative.objects.filter(level='senate').update(level='us_senate')


def backwards(apps, schema_editor):
    Representative = apps.get_model('representatives', 'Representative')
    Representative.objects.filter(level='us_house').update(level='house')
    Representative.objects.filter(level='us_senate').update(level='senate')


class Migration(migrations.Migration):

    dependencies = [
        ('representatives', '0008_notification'),
    ]

    operations = [
        # Schema first: widen max_length and update choices to accept new values.
        migrations.AlterField(
            model_name='representative',
            name='level',
            field=models.CharField(choices=[('us_house', 'US House'), ('us_senate', 'US Senate'), ('state_house', 'State House'), ('state_senate', 'State Senate'), ('governor', 'Governor')], db_index=True, max_length=20),
        ),
        # Data migration: rename existing rows to namespaced values.
        migrations.RunPython(forwards, backwards),
    ]
