import re
import logging
from django.conf import settings
from django.core.cache import cache
from rest_framework import viewsets, status
from rest_framework.decorators import action
from rest_framework.response import Response
from rest_framework.throttling import AnonRateThrottle
from rest_framework.views import APIView
from .errors import error_response
from .throttles import ZipcodeLookupThrottle, VotesThrottle, LegislationThrottle

from .models import Representative, SyncStatus
from .services.auto_sync import trigger_sync_if_stale
from .serializers import RepresentativeListSerializer, RepresentativeDetailSerializer, SyncStatusSerializer
from .integrations.zip_lookup import fetch_reps_by_zipcode, geocode_zip
from .integrations.census import (
    fetch_congressional_districts, fetch_state_boundary, STATE_FIPS,
    load_local_congressional_districts,
)
from .services.congress_api import fetch_recent_votes, fetch_sponsored_legislation, fetch_cosponsored_legislation

logger = logging.getLogger(__name__)

ZIPCODE_RE = re.compile(r'^\d{5}$')
BIOGUIDE_RE = re.compile(r'^[A-Z]\d{6}$')


class RepresentativeViewSet(viewsets.ReadOnlyModelViewSet):
    # Read-only endpoints for the map and detail panel.
    queryset = Representative.objects.all()

    def get_serializer_class(self):
        # Use the smaller serializer for list views and the richer serializer for detail views.
        if self.action == 'retrieve':
            return RepresentativeDetailSerializer
        return RepresentativeListSerializer

    def get_throttles(self):
        if self.action == 'list':
            # ZIP-scoped lookups hit the external Civic API — tighter limit.
            if self.request.query_params.get('zipcode'):
                return [ZipcodeLookupThrottle()]
            # Bulk list is the scraping surface — apply the global anon rate.
            return [AnonRateThrottle()]
        return super().get_throttles()

    def list(self, request):
        # Opportunistically refresh stale data without blocking the response.
        trigger_sync_if_stale()
        zipcode = request.query_params.get('zipcode', '').strip()

        if zipcode:
            if not ZIPCODE_RE.match(zipcode):
                return error_response('Invalid zipcode format.')
            return self._handle_zipcode_request(zipcode)

        # Default: return all reps
        queryset = Representative.objects.all()
        serializer = RepresentativeListSerializer(queryset, many=True)
        return Response(serializer.data)

    def _handle_zipcode_request(self, zipcode):
        try:
            # Resolve one ZIP code into its House seat plus the state's senators.
            reps = fetch_reps_by_zipcode(zipcode)
        except Exception as e:
            logger.warning("ZIP lookup error for %s: %s", zipcode, e)
            return error_response(
                'Representative lookup is temporarily unavailable. Please try again later.',
                status=status.HTTP_503_SERVICE_UNAVAILABLE,
            )

        if not reps:
            return error_response(
                'No federal representatives found for that ZIP code.',
                status=status.HTTP_404_NOT_FOUND,
            )

        serializer = RepresentativeListSerializer(reps, many=True)
        return Response(serializer.data)


def _validate_state(state_raw: str):
    """Return uppercased state abbreviation or None if invalid."""
    state = state_raw.upper().strip()
    if state in STATE_FIPS:
        return state
    return None


class DistrictViewSet(viewsets.ViewSet):
    # Geometry endpoints used by the frontend map layers.
    @action(detail=False, methods=['get'], url_path='congressional')
    def congressional(self, request):
        state = _validate_state(request.query_params.get('state', ''))
        if not state:
            return error_response('Valid 2-letter state abbreviation required.')

        cache_key = f'district_geojson_v2_{state}'  # v2: simplified geometry (0.01° offset)
        try:
            cached = cache.get(cache_key)
            if cached:
                # District GeoJSON is large enough that a cache hit is worth checking first.
                return Response(cached)
        except Exception:
            logger.warning("Cache unavailable for %s, fetching directly", cache_key)

        # Serve from pre-built local file (generated by `build_district_data` command).
        local_data = load_local_congressional_districts(state)
        if local_data is not None:
            try:
                cache.set(cache_key, local_data, 60 * 60 * 24 * 7)  # 7 days
            except Exception:
                pass
            return Response(local_data)

        # No local file — fall back to live Census only if explicitly enabled.
        if not settings.DISTRICT_LIVE_FALLBACK:
            logger.warning("District data missing for %s and live fallback is disabled", state)
            return error_response(
                f'District data for {state} is not available. Run: python manage.py build_district_data',
                status=status.HTTP_503_SERVICE_UNAVAILABLE,
            )

        try:
            geojson = fetch_congressional_districts(state)
            try:
                cache.set(cache_key, geojson, 60 * 60 * 24 * 7)  # 7 days
            except Exception:
                pass
            return Response(geojson)
        except Exception:
            logger.exception("Failed to fetch congressional districts for %s", state)
            return error_response('Failed to fetch district data.', status=status.HTTP_500_INTERNAL_SERVER_ERROR)

    @action(detail=False, methods=['get'], url_path='state-boundary')
    def state_boundary(self, request):
        state = _validate_state(request.query_params.get('state', ''))
        if not state:
            return error_response('Valid 2-letter state abbreviation required.')

        cache_key = f'state_boundary_{state}'
        try:
            cached = cache.get(cache_key)
            if cached:
                return Response(cached)
        except Exception:
            logger.warning("Cache unavailable for %s, fetching directly", cache_key)

        try:
            geojson = fetch_state_boundary(state)
            try:
                cache.set(cache_key, geojson, 60 * 60 * 24 * 7)  # 7 days
            except Exception:
                pass
            return Response(geojson)
        except Exception:
            logger.exception("Failed to fetch state boundary for %s", state)
            return error_response('Failed to fetch boundary data.', status=status.HTTP_500_INTERNAL_SERVER_ERROR)


class SyncStatusView(APIView):
    """GET /api/sync-status/ — returns the current sync state of representative data."""

    def get(self, request):
        sync_status = SyncStatus.objects.first()
        if sync_status is None:
            return Response({
                'last_synced_at': None,
                'is_syncing': False,
                'data_age_seconds': None,
            })
        serializer = SyncStatusSerializer(sync_status)
        return Response(serializer.data)


class VotesView(APIView):
    """GET /api/representatives/{bioguide_id}/votes/ — recent votes from Congress.gov."""
    throttle_classes = [VotesThrottle]

    def get(self, request, bioguide_id: str):
        if not BIOGUIDE_RE.match(bioguide_id):
            return error_response('Invalid bioguide_id format.')
        votes = fetch_recent_votes(bioguide_id)
        return Response(votes)


class LegislationView(APIView):
    """GET /api/representatives/{bioguide_id}/legislation/ — sponsored and cosponsored bills."""
    throttle_classes = [LegislationThrottle]

    def get(self, request, bioguide_id: str):
        if not BIOGUIDE_RE.match(bioguide_id):
            return error_response('Invalid bioguide_id format.')
        if not settings.CONGRESS_API_KEY:
            return Response(
                {'detail': 'Legislation source unavailable — CONGRESS_API_KEY not configured.'},
                status=status.HTTP_503_SERVICE_UNAVAILABLE,
            )
        return Response({
            'sponsored': fetch_sponsored_legislation(bioguide_id),
            'cosponsored': fetch_cosponsored_legislation(bioguide_id),
        })


class HealthView(APIView):
    """GET /api/health/ — liveness and DB connectivity check for load balancers."""
    authentication_classes = []
    permission_classes = []
    throttle_classes = []  # load balancers must never be rate-limited

    def get(self, request):
        try:
            Representative.objects.exists()
        except Exception:
            return Response({'status': 'error', 'db': 'error'}, status=status.HTTP_500_INTERNAL_SERVER_ERROR)
        return Response({'status': 'ok', 'db': 'ok'})


class ZipLookupView(APIView):
    """GET /api/zip-lookup/?zipcode=12345 — returns {lat, lng} for a ZIP code centroid."""

    def get(self, request):
        zipcode = request.query_params.get('zipcode', '').strip()
        if not ZIPCODE_RE.match(zipcode):
            return error_response('Enter a valid 5-digit ZIP code.')
        try:
            # This endpoint only returns map coordinates; it does not fetch representatives.
            lat, lng = geocode_zip(zipcode)
        except Exception as e:
            logger.warning("ZIP geocode error for %s: %s", zipcode, e)
            return error_response(
                'Could not look up that ZIP code. Please try again.',
                status=status.HTTP_503_SERVICE_UNAVAILABLE,
            )
        if lat is None:
            return error_response('ZIP code not found.', status=status.HTTP_404_NOT_FOUND)
        return Response({'lat': lat, 'lng': lng})


class ConfigView(APIView):
    """GET /api/v1/config/ — public runtime config for the frontend.

    Returns the Mapbox token from the server environment so it is never
    embedded in the JS bundle.  The token is read-only and carries no user
    data, so no authentication is required.  The global AnonRateThrottle
    (100/day) applies; a legitimate frontend calls this once per session.
    """

    def get(self, request):
        return Response({'mapbox_token': settings.MAPBOX_TOKEN})
